name: Simple pipeline

on:
  push:
    paths:
      - '**/Program.cs'

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with: 
        dotnet-version: 8.0

    - name: build project
      run: dotnet build path/to/your/project.csproj
